version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8.3

    working_directory: ~/fastify-website

    steps:
      - checkout

      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          - v1-dependencies-

      - run:
          name: Install dependencies
          command: npm install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run:
          name: Test
          command: npm test

      - run:
          name: Build
          command: npm run build

      - deploy:
          command: |
            # this part will be moved inside the if (master) block before the merge
            echo "$DOMAIN" > CNAME
            cp -rf .circleci build
            git config --global user.email "$GH_EMAIL"
            git config --global user.name "$GH_NAME"
            NODE_DEBUG=gh-pages npm run deploy
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              sudo apt-get install -y python python-dev python-virtualenv
              mkdir aws
              virtualenv aws/env
              source aws/env/bin/activate
              aws/env/bin/pip install awscli
              npm run publish
            else
              echo "Not master branch so not deploying"
            fi
